### ISSUE TITLE
<WARNING>p5.js seems to have been imported multiple times.

### ISSUE THREAD

**Issue by GoToLoop** [AliaNeedsHelp/Bathtub-Simulator#1]
This is about your issue from: https://github.com/processing/p5.js/issues/4985

Workaround for it:
```js
window.mocha = 'Hack to block p5.js auto global instantiation.';
new p5; // Prematurely instantiates p5.js so its props are available now.
window._setupDone = undefined; // Blocks duplicate instantiation warn.
```

An online example sketch:
https://www.OpenProcessing.org/sketch/955445

Official forum for all Processing's flavors including p5*js:
https://Discourse.Processing.org/

**Comment by AliaNeedsHelp** [comment]
Thank you so much!
